### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by snocl** [freelan-developers/website#1]
Currently the links to the specification on [here](http://freelan.org/) (under "You have nothing to hide...") and [here](http://freelan.org/development.html) are dead.

They link to the old `https://raw.githubusercontent.com/freelan-developers/libfscp/master/libs/fscp/fscp.txt` instead of the new `https://raw.githubusercontent.com/freelan-developers/freelan/master/fscp.txt`.

**Comment by ereOn** [comment]
@snorr Thanks for this. You are right that the links need be fixed. Will do it this evening.
