### ISSUE TITLE
Update download links

### ISSUE THREAD

**Issue by Tidro** [freelan-developers/website#3]
Maybe i missing something, but its already 2.0?
https://github.com/freelan-developers/freelan/releases

Still 1.1 on site.

**Comment by leggewie** [comment]
ping @ereOn 

Should we drop Win XP support and link to the binaries on github instead?  I guess freelan 1.1 is dead/unsupported and not forward-compatible.

**Comment by ereOn** [comment]
@leggewie Microsoft itself doesn't support WinXP anymore. I think it's safe to drop support as well.

**Comment by s-vincent** [comment]
+1, we should update the website. It confuses users because they go to the website, download the "only available" 1.1 version, have issues and then we tell them that this version is not supported anymore.

**Comment by ereOn** [comment]
@leggewie @s-vincent I finally could update the website...

I had to find back my credentials, not only for the website but for the place where I store the binaries (and that provides download stats as well).

Sorry it took so long. Everything should be okay now !

**Comment by s-vincent** [comment]
We let this issue opened until 2.1 release is out and download links updated as well (to avoid to forget it ;).

**Comment by s-vincent** [comment]
Fixed in 0f9d2a21330371ce259598138a271c86395c83ec.
